### ISSUE TITLE
[sdk/javascript] NetworkTimestamp - failing when adding hours/minutes/seconds/milliseconds

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/symbol#195]
When adding time (e.g. hours) to existing NetworkTimestamp I got the error: `TypeError: Cannot mix BigInt and other types, use explicit conversions`

```
const { symbol } = require('symbol-sdk');

let timestamp = new symbol.NetworkTimestamp(100n)
timestamp.addHours(2n) <-- This throws error that I can add 
```

Stack trace:

```
/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/NetworkTimestamp.js:45
                return this.addMinutes(60 * count);
                                          ^

TypeError: Cannot mix BigInt and other types, use explicit conversions
    at NetworkTimestamp.addHours (/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/NetworkTimestamp.js:45:29)
    at Object.<anonymous> (/home/comp/Developer/git/example2/SendTestTransaction.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

I tried also with int but it failed when constructing a transaction (so the problem may be here):

```
const {CryptoTypes} = require("symbol-sdk");
const { SymbolFacade } = require('symbol-sdk').facade;
const { symbol } = require('symbol-sdk');

const timestamp = new symbol.NetworkTimestamp(123123123);
const facade = new SymbolFacade('testnet');
const keyPair = new SymbolFacade.KeyPair(CryptoTypes.PrivateKey.random());

const transaction = facade.transactionFactory.create({
	type: 'transfer_transaction',
	signerPublicKey: keyPair.publicKey.toString(),
	recipientAddress: 'TDQF2JY4LLTGHUMA44YM4ZLVER7ZNLAKIPOG7JY',
	fee: 0n,
	deadline: timestamp.addHours(1),
	mosaics: [
		{
			mosaicId: BigInt('0x3A8416DB2D53B6C8'),
			amount: BigInt(1000000)
		}
	],
	message: '\0'+'test' // 0 is message type - plain text
});
```
Stack trace:

```
/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/BaseValue.js:8
                        throw new TypeError(`"value" (${value}) has invalid type, expected BigInt`);
                        ^

TypeError: "value" (126723123) has invalid type, expected BigInt
    at check (/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/BaseValue.js:8:10)
    at new BaseValue (/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/BaseValue.js:40:16)
    at new Timestamp (/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/symbol/models.js:201:3)
    at /home/comp/Developer/git/example2/node_modules/symbol-sdk/src/RuleBasedTransactionFactory.js:88:70
    at TransactionDescriptorProcessor._lookupValueAndApplyTypeHints (/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/TransactionDescriptorProcessor.js:25:47)
    at TransactionDescriptorProcessor.lookupValue (/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/TransactionDescriptorProcessor.js:36:22)
    at /home/comp/Developer/git/example2/node_modules/symbol-sdk/src/TransactionDescriptorProcessor.js:55:23
    at Array.forEach (<anonymous>)
    at TransactionDescriptorProcessor.copyTo (/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/TransactionDescriptorProcessor.js:48:58)
    at RuleBasedTransactionFactory.createFromFactory (/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/RuleBasedTransactionFactory.js:185:13)
```

**Comment by Jaguar0625** [comment]
Fixed in 508573b6ffacff7ea15c22daae31fa1af8d16bbb.
