### ISSUE TITLE
[sdk/javascript] sending transaction - error for unordered mosaics array

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/symbol#206]
When a mosaic array is not ordered by mosaic_id when constructing a transaction we get the error: "array passed to write array is not sorted". SDK should handle sorting and not require to sort it by the developer which is using SDK.

Example code causing the error:

```
const transaction = facade.transactionFactory.create({
		type: 'transfer_transaction',
		signerPublicKey: keyPair.publicKey.toString(),
		recipientAddress: recipientAddress,
		fee: 0n,
		deadline: getDeadline(),
		mosaics: [
			{
				mosaicId: BigInt('0x6BED913FA20223F8'),
				amount: BigInt(amountInAtomicUnit)
			},{
				mosaicId: BigInt('0x170B5916F65E13DC'),
				amount: BigInt(amountInAtomicUnit)
			}
		]
	});

```

Result:
Error: 

```
(node:83507) UnhandledPromiseRejectionWarning: RangeError: array passed to write array is not sorted
    at writeArrayImpl (/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/utils/arrayHelpers.js:31:10)
    at Object.writeArray (/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/utils/arrayHelpers.js:126:3)
    at TransferTransaction.serialize (/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/symbol/models.js:11176:16)
    at SymbolFacade.signTransaction (/home/comp/Developer/git/example2/node_modules/symbol-sdk/src/facade/SymbolFacade.js:89:41)
```

Expected result:
SDK should handle sorting of mosaic array internally (if it's required to serialize sorted).

Used SDK version: 3.0.0

Corresponding issue for Python SDK: #205

**Comment by gimre-xymcity** [comment]
auto-sorting for create() is now default behavior, js sdk 3.0.4

**Comment by cryptoBeliever** [comment]
Works correctly with unordered mosaics list. Example tx:

```
const transaction = facade.transactionFactory.create({
        type: 'transfer_transaction_v1',
        signerPublicKey: keyPair.publicKey.toString(),
        recipientAddress: 'TCJVHYTL32T4KOHSU55I6EPLWMAJCFXRNRCVJXA',
        fee: 100000n,
        deadline: BigInt(timestamp + 3600n * 1000n), // 3600sec * 1000ms
        mosaics: [
            {
                mosaicId: BigInt('0x3B6C1884BB157E22'),
                amount: BigInt(100)
            },
            {
                mosaicId: BigInt('0x11A883250997A39A'),
                amount: BigInt(100)
            }
        ],
        message: '\0'+'some message' // 0 is message type - plain text
    });
```
